export default {
  flavor: "Affogato",
  tokenColors: [
    { name: "Punctuation", scope: ["punctuation"], foreground: "neutral.fg0" },
    { name: "Comments", scope: ["comment", "punctuation.definition.comment"], foreground: "neutral.gray0" },
    { name: "Variables and parameters", scope: ["variable", "variable.parameter", "meta.definition.variable.name", "meta.parameters variable"], foreground: "neutral.fg0" },
    { name: "Properties and fields", scope: ["variable.other.property", "meta.object-literal.key", "support.type.property-name"], foreground: "neutral.fg0" },
    { name: "Numbers, booleans, and constants", scope: ["constant", "support.constant", "variable.other.constant"], foreground: "colors.purple" },
    { name: "Strings", scope: ["string", "string.quoted", "string.template"], foreground: "colors.yellow" },
    { name: "String interpolation", scope: ["punctuation.definition.template-expression", "punctuation.section.embedded", "variable.interpolation"], foreground: "neutral.fg0" },
    { name: "Keywords", scope: ["keyword", "storage.type", "storage.modifier"], foreground: "colors.red" },
    { name: "Operators", scope: ["keyword.operator", "punctuation.separator.namespace", "punctuation.accessor.namespace"], foreground: "colors.orange" },
    { name: "Functions and methods", scope: ["entity.name.function", "entity.name.method", "support.function", "variable.function", "meta.function-call"], foreground: "colors.green" },
    { name: "Modules and namespaces", scope: ["entity.name.namespace", "entity.name.module", "entity.name.type.module", "support.module", "variable.other.module"], foreground: "colors.cyan" },
    { name: "Types, classes, and traits", scope: ["entity.name.type", "entity.name.class", "entity.name.struct", "entity.name.enum", "entity.name.interface", "entity.name.trait", "entity.other.inherited-class", "support.type", "support.class", "support.type.trait"], foreground: "colors.blue" },
    { name: "Decorators and annotations", scope: ["meta.decorator", "meta.annotation", "punctuation.decorator", "entity.name.function.decorator"], foreground: "colors.red" },
    { name: "Tags", scope: ["entity.name.tag"], foreground: "colors.red" },
    { name: "Attributes", scope: ["entity.other.attribute-name", "support.type.property-name.css"], foreground: "colors.blue" },
    { name: "Labels and special symbols", scope: ["entity.name.label", "constant.other.symbol", "constant.other.key"], foreground: "colors.purple" },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], foreground: "bright.red" },
    { name: "Deprecated", scope: ["invalid.deprecated", "entity.name.function.preprocessor"], foreground: "neutral.gray0", fontStyle: "strikethrough" },
    { name: "Markup headings", scope: ["markup.heading", "entity.name.section.markdown", "punctuation.definition.heading.markdown"], foreground: "colors.blue" },
    { name: "Markup bold", scope: ["markup.bold", "markup.bold string"], foreground: "colors.red" },
    { name: "Markup italic", scope: ["markup.italic", "markup.italic string"], foreground: "colors.purple" },
    { name: "Markup links", scope: ["markup.underline.link", "string.other.link", "string.other.link.title.markdown"], foreground: "colors.cyan", fontStyle: "underline" },
    { name: "Markup inline code", scope: ["markup.inline.raw", "markup.inline.raw.string.markdown"], foreground: "colors.yellow" },
    { name: "Markup quote", scope: ["markup.quote", "punctuation.definition.blockquote.markdown"], foreground: "neutral.gray0" },
    { name: "Markup inserted", scope: ["markup.inserted", "markup.inserted.git_gutter"], foreground: "colors.green" },
    { name: "Markup changed", scope: ["markup.changed", "markup.changed.git_gutter"], foreground: "colors.orange" },
    { name: "Markup deleted", scope: ["markup.deleted", "markup.deleted.git_gutter"], foreground: "colors.red" },
  ],
  semanticTokenColors: {
    namespace: "colors.cyan",
    type: "colors.blue",
    class: "colors.blue",
    enum: "colors.blue",
    interface: "colors.blue",
    struct: "colors.blue",
    typeParameter: "colors.blue",
    parameter: "neutral.fg0",
    variable: "neutral.fg0",
    property: "neutral.fg0",
    enumMember: "colors.purple",
    event: "colors.green",
    function: "colors.green",
    method: "colors.green",
    macro: "colors.green",
    label: "colors.purple",
    comment: "neutral.gray0",
    string: "colors.yellow",
    keyword: "colors.red",
    number: "colors.purple",
    regexp: "colors.yellow",
    operator: "colors.orange",
    decorator: "colors.red",
    "variable.readonly": "colors.purple",
    "property.readonly": "neutral.fg0",
    "*.deprecated": { foreground: "neutral.gray0", strikethrough: true },
  },
};
