export default {
  flavor: "Sorbet",
  tokenColors: [
    { name: "Comments", scope: ["comment", "punctuation.definition.comment"], foreground: "neutral.gray1" },
    { name: "Variables", scope: ["variable", "meta.definition.variable.name"], foreground: "neutral.fg0" },
    { name: "Language variables", scope: ["variable.language", "variable.language.this", "variable.language.super"], foreground: "colors.red" },
    { name: "Parameters", scope: ["variable.parameter", "meta.parameters variable"], foreground: "colors.orange" },
    { name: "Properties", scope: ["variable.other.property", "meta.object-literal.key", "support.type.property-name"], foreground: "neutral.fg0" },
    { name: "Constants", scope: ["constant", "support.constant", "variable.other.constant"], foreground: "colors.orange" },
    { name: "Numbers and booleans", scope: ["constant.numeric", "constant.language.boolean", "constant.language.null", "constant.language.undefined"], foreground: "colors.orange" },
    { name: "Strings", scope: ["string", "string.quoted", "string.template"], foreground: "colors.green" },
    { name: "String interpolation", scope: ["punctuation.definition.template-expression", "punctuation.section.embedded", "variable.interpolation"], foreground: "colors.cyan" },
    { name: "Regular expressions", scope: ["string.regexp", "constant.other.character-class.regexp", "keyword.operator.quantifier.regexp"], foreground: "colors.cyan" },
    { name: "Escape characters", scope: ["constant.character.escape", "constant.other.placeholder"], foreground: "bright.cyan" },
    { name: "Keywords", scope: ["keyword", "storage.type", "storage.modifier"], foreground: "colors.purple" },
    { name: "Control flow", scope: ["keyword.control", "keyword.control.flow", "keyword.control.conditional", "keyword.control.loop"], foreground: "colors.purple" },
    { name: "Operators", scope: ["keyword.operator", "punctuation.separator", "punctuation.accessor"], foreground: "colors.cyan" },
    { name: "Functions and methods", scope: ["entity.name.function", "entity.name.method", "support.function", "variable.function", "meta.function-call"], foreground: "colors.blue" },
    { name: "Types and classes", scope: ["entity.name.type", "entity.name.class", "entity.name.struct", "entity.name.enum", "entity.name.interface", "support.type", "support.class"], foreground: "colors.yellow" },
    { name: "Inherited types", scope: ["entity.other.inherited-class", "entity.name.type.module", "entity.name.namespace"], foreground: "colors.yellow" },
    { name: "Decorators and annotations", scope: ["meta.decorator", "meta.annotation", "punctuation.decorator", "entity.name.function.decorator"], foreground: "colors.purple" },
    { name: "Tags", scope: ["entity.name.tag", "punctuation.definition.tag"], foreground: "colors.red" },
    { name: "Attributes", scope: ["entity.other.attribute-name", "support.type.property-name.css"], foreground: "colors.yellow" },
    { name: "Labels and special symbols", scope: ["entity.name.label", "constant.other.symbol", "constant.other.key"], foreground: "colors.brown" },
    { name: "Invalid", scope: ["invalid", "invalid.illegal"], foreground: "bright.red" },
    { name: "Deprecated", scope: ["invalid.deprecated", "entity.name.function.preprocessor"], foreground: "neutral.gray0", fontStyle: "strikethrough" },
    { name: "Markup headings", scope: ["markup.heading", "entity.name.section.markdown", "punctuation.definition.heading.markdown"], foreground: "colors.yellow" },
    { name: "Markup bold", scope: ["markup.bold", "markup.bold string"], foreground: "bright.red" },
    { name: "Markup italic", scope: ["markup.italic", "markup.italic string"], foreground: "bright.purple" },
    { name: "Markup links", scope: ["markup.underline.link", "string.other.link", "string.other.link.title.markdown"], foreground: "colors.blue", fontStyle: "underline" },
    { name: "Markup inline code", scope: ["markup.inline.raw", "markup.inline.raw.string.markdown"], foreground: "colors.cyan" },
    { name: "Markup quote", scope: ["markup.quote", "punctuation.definition.blockquote.markdown"], foreground: "neutral.gray2" },
    { name: "Markup inserted", scope: ["markup.inserted", "markup.inserted.git_gutter"], foreground: "colors.green" },
    { name: "Markup changed", scope: ["markup.changed", "markup.changed.git_gutter"], foreground: "colors.orange" },
    { name: "Markup deleted", scope: ["markup.deleted", "markup.deleted.git_gutter"], foreground: "colors.red" },
  ],
  semanticTokenColors: {
    namespace: "colors.yellow",
    type: "colors.yellow",
    class: "colors.yellow",
    enum: "colors.yellow",
    interface: "colors.yellow",
    struct: "colors.yellow",
    typeParameter: "bright.yellow",
    parameter: "colors.orange",
    variable: "neutral.fg0",
    property: "neutral.fg0",
    enumMember: "colors.orange",
    event: "colors.brown",
    function: "colors.blue",
    method: "colors.blue",
    macro: "colors.purple",
    label: "colors.brown",
    comment: "neutral.gray1",
    string: "colors.green",
    keyword: "colors.purple",
    number: "colors.orange",
    regexp: "colors.cyan",
    operator: "colors.cyan",
    decorator: "colors.purple",
    "variable.readonly": "colors.orange",
    "property.readonly": "colors.orange",
    "*.deprecated": { foreground: "neutral.gray0", strikethrough: true },
    "*.defaultLibrary": { foreground: "colors.brown" },
  },
};
