name: Gelato
variant: dark

neutral:
  bg0: "#211E1D"
  bg1: "#2B2725"
  bg2: "#393330"

  gray0: "#6C6560"
  gray1: "#7C746E"
  gray2: "#A39C94"

  fg0: "#D8D4C8"
  fg1: "#E9E4D7"
  fg2: "#F7F1E3"

colors:
  red: "#E99B91"
  orange: "#EAAF84"
  yellow: "#F2D98B"
  green: "#A8CC91"
  cyan: "#99D5CE"
  blue: "#9FC7EA"
  purple: "#C5AFE2"
  brown: "#C58F78"

bright:
  red: "#F3B1A7"
  orange: "#F3C39C"
  yellow: "#F8E5A2"
  green: "#BDDEA9"
  cyan: "#AFE5DF"
  blue: "#B8D8F3"
  purple: "#D8C4ED"

special:
  cursor: "#E0DAB9"
